version: '3.9'
services:
  django:
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    volumes:
      - ./src:/src
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD}"
      POSTGRES_USER: "${DOCKER_POSTGRES_USER}"
      POSTGRES_DB: "${DOCKER_POSTGRES_DB_NAME}"
      
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      POSTGRES_PASSWORD: "${DOCKER_POSTGRES_PASSWORD}"
      POSTGRES_USER: "${DOCKER_POSTGRES_USER}"
      POSTGRES_DB: "${DOCKER_POSTGRES_DB_NAME}"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: